=== alex-tilo/api-param/src/test/resources/token/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "token_type":     {"type": "string"},
    "expires_in":     {"type": "integer", "pattern": "^(900)$" },
    "access_token":   {"type": "string"},
    "scope":          {"type": "string"},
    "refresh_token":  {"type": "string"},
    "id_token":       {"type": "string"}
  },
  "required": [
    "token_type",
    "expires_in",
    "access_token",
    "scope",
    "refresh_token",
    "id_token"
  ]
}

=== alex-tilo/api-param/src/test/resources/token/response.json
{
    "token_type": "Bearer",
    "expires_in": 900,
    "access_token": "eyJraWQiOiJHT1RLUXY2NG40N3ZRVjVuaGNGSVVveVNtaWhtQTM5V0N4TFNxVXY4WFVrIiwiYWxnIjoiUlMyNTYifQ.eyJ2ZXIiOjEsImp0aSI6IkFULkdsZkVQb1BISVVxOXRGUkZ0UUlLdkRCc1BMWndmZFhkNmV0SmJ6bDN1SHcub2FyeGg4amc4NHhRcmJza2UwaDYiLCJpc3MiOiJodHRwczovL2Ficy1xYTEub2t0YXByZXZpZXcuY29tL29hdXRoMi9hdXNkdnV5Y3VsUklZaXRYZzBoNyIsImF1ZCI6IkFsYmVydHNvbnMiLCJpYXQiOjE2MTQ2NjczMjQsImV4cCI6MTYxNDY2ODIyNCwiY2lkIjoiMG9hZDhhaXd0N1pBN3NXY3owaDciLCJ1aWQiOiIwMHV0cnA5aTE1MGYyeU9kbTBoNyIsInNjcCI6WyJwcm9maWxlIiwib2ZmbGluZV9hY2Nlc3MiLCJvcGVuaWQiXSwiemlwIjoiOTQ1NjgiLCJzdWIiOiJhY2h6dHBAZ21haWwuY29tIiwiaGlkIjoiNzI5MDA1ODU1MDYyIiwiZG5tIjoiYWNoIiwiYWxuIjoiNDkxMjgwMjE2MzgiLCJnaWQiOiI1NTctMDY1LTE1OTkyNDg5OTc3MjEiLCJmbm0iOiJhY2giLCJlY2MiOiIiLCJsbm0iOiJ6dHAiLCJqcHIiOiIiLCJ1dWlkIjoiYmYyMGU1ZWEtNTE0ZS00ZjEzLWFiMDktZmQ4M2E3NzhiYmU3IiwiYmFuIjoic2FmZXdheSIsInN0ciI6IjE5NTMiLCJwaG4iOiI5MjU2Mzk1NjQwIiwiYmlkIjoiIn0.FWLTowcocb3KJH7dO-e_ntTSA4CTf1IDIuDHhH86UvAwJO5rUwtuezGYPc6mVhWSnVLCNd8xmdJcNVoiN1SVgr1L_HXTKmHlyX3ukqUZ8U2wgtn99oOECvZlxchtdmPdhbipdBzmoAvrrCD4gdl-OYdDC_6h83LaQ3NlEBAOkyeDeexWHx5Mf-bNJRXaD1cDH2QfojJNPBUjqBCu_bn8NNqPi7uEfZfvdV0dJbHjXeSp0AQ5ze3rzrvxfEbFYR1T1GSuu8fykmtfL7as7wdoW72SR7O-uPqi2WcrtJMjUvzGRfj8gPtepMsasDtbZ8fu_RZMaFNKG8ZM3At4q1MJKQ",
    "scope": "profile offline_access openid",
    "refresh_token": "Wo4flS0W_TYLxBE5PVTRWMuM6B_IAzn5vGQPORaDwqQ",
    "id_token": "eyJraWQiOiJHT1RLUXY2NG40N3ZRVjVuaGNGSVVveVNtaWhtQTM5V0N4TFNxVXY4WFVrIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiIwMHV0cnA5aTE1MGYyeU9kbTBoNyIsIm5hbWUiOiJhY2ggenRwIiwidmVyIjoxLCJpc3MiOiJodHRwczovL2Ficy1xYTEub2t0YXByZXZpZXcuY29tL29hdXRoMi9hdXNkdnV5Y3VsUklZaXRYZzBoNyIsImF1ZCI6IjBvYWQ4YWl3dDdaQTdzV2N6MGg3IiwiaWF0IjoxNjE0NjY3MzI0LCJleHAiOjE2MTQ2NzA5MjQsImp0aSI6IklELmt4WlpzUFVjN1M3RnotMTVhN0I2RkVDWlIzeHgtQVVJMFBXQkhPRmxMN00iLCJhbXIiOlsicHdkIl0sImlkcCI6IjAwb2MzdnJldmE4dnc1Y3ZoMGg3IiwicHJlZmVycmVkX3VzZXJuYW1lIjoiYWNoenRwQGdtYWlsLmNvbSIsImF1dGhfdGltZSI6MTYxNDY2NzMyNCwiYXRfaGFzaCI6InJVMmwtbUp2bVZKb0lFX3VONWFEbkEifQ.YQG4ABCfGoAWNHhfD3mp6Jg1P-hGZbBSkYV-YAnPxXMeg4HKc-u5qlfhTyCKjMg3ehOarqQmNsTQGL3vlcHi6DV4-E7XDFXprsfPwJHN47xEBQtu-R4w1VnH8q483OwVZxxq3n7r3UlF5gifqW1PKBfjbrDdkvU01Km90vt9a6bZr6VPww0aHd1tSHLKUVCJdMwH5xtH2l3P-k8qBagXOx6JFg7k_TZanjlBOJr_u2VQ3AvFcvj4j3nCRiGkz3Vgx32WUAB3yEbLD21y5UlTWMFAUsaYxhX-Xw6ZQjFL9mQbWoORS3xZAfhkOwhQbE-5yyQ9mgp82HT3PPrvT21OZg"
}
